#pragma once

enum eObjet { PRIMITIVE, BILLBOARD, FLOOR, CUSTOM, PHYSPRIMITIVE, PHYSICCUSTOM, XMESH, PHYSICXMESH, PHYSICXSTATIC, DUPLICATEMESH, TEXT, VERTEXSTRIP, ACTOR, NONE, V1_5 };
enum ePHYSMAT  { DEF_PHYSMAT, WALL, FINISH, GROUND, BALL, HUMAN };
enum eMATERIAL  { DEF_MATERIAL, TRANSLUCENT, MATE, METAL_SHINE, GLASS };  // TODO : is it used??
enum eGeometry { CUBE, SPHERE, CYLINDER, CONE, TEAPOT, PLANE, NON_PRIMITIVE, CUSTOM_MESH };

static const char* eObjet_names[] = { "PRIMITIVE", "BILLBOARD", "FLOOR", "CUSTOM", "PHYSPRIMITIVE", "PHYSICCUSTOM", "XMESH", "PHYSICXMESH", "PHYSICXSTATIC", "DUPLICATEMESH", "TEXT", "VERTEXSTRIP", "ACTOR", "NONE", "V1_5" };
static const char* ePhysmat_names[] = { "DEF_PHYSMAT", "WOOD", "FINISH", "LEVEL", "BALL", "ELEVATOR" };
static const char* eMaterial_names[] = { "DEF_MATERIAL", "TRANSLUCENT", "GLASS", "MATE", "METAL_SHINE" };
static const char* eGeometry_names[] = { "CUBE", "SPHERE", "CYLINDER", "CONE", "TEAPOT", "PLANE", "NON_PRIMITIVE", "NONE" };
